ALTER TABLE schedules ADD COLUMN IF NOT EXISTS release_name_template VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE triggers ADD COLUMN IF NOT EXISTS release_name_template VARCHAR(255) NOT NULL DEFAULT '';
