ktor:
  deployment:
    port: 8080
    host: 0.0.0.0
  application:
    modules:
      - com.github.mr3zee.ApplicationKt.module

app:
  database:
    url: "jdbc:postgresql://localhost:5432/release_wizard"
    user: "postgres"
    password: "postgres"
    driver: "org.postgresql.Driver"
  auth:
    username: "admin"
    password: "admin"
    sessionSignKey: "6162636465666768696a6b6c6d6e6f707172737475767778797a313233343536"
  encryption:
    key: "YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY="
